import type { BrainImportItem, BrainItem, BrainSnapshot } from "@/lib/brain-types";

export const publicBrainSeed: BrainImportItem[] = [
  {
    id: "identity-aaron",
    kind: "memory",
    area: "Identity",
    title: "Aaron Allton",
    summary: "Founder and builder behind iLLCo Ai, iLLCo Command, and the M3ntally-iLL creative catalog. Based in Henderson, Nevada.",
    status: "active",
    priority: "high",
    tags: ["identity", "founder", "henderson"],
    source: "ChatGPT memory",
  },
  {
    id: "brand-illco-ai",
    kind: "system",
    area: "Business",
    title: "iLLCo Ai operating identity",
    summary: "AI agents, automations, apps, video systems, and creative workflows for creators, entrepreneurs, service providers, and small businesses.",
    status: "active",
    priority: "critical",
    tags: ["illco-ai", "brand", "automation"],
    source: "Business plan",
    sourceUrl: "https://illcoai.tech",
  },
  {
    id: "project-illco-command",
    kind: "project",
    area: "Business",
    title: "iLLCo Command",
    summary: "Primary public application, app store, account system, product catalog, and command workspace. This Brain OS is being added here as /brain.",
    status: "active",
    priority: "critical",
    tags: ["nextjs", "app-store", "command-center"],
    source: "GitHub",
    sourceUrl: "https://github.com/D0ubl3-A/illco-command",
  },
  {
    id: "project-lyric-forge",
    kind: "project",
    area: "Creative Systems",
    title: "Lyric Video Forge",
    summary: "ChatGPT-ready lyric-video workflow using transcription, word timing, visual planning, rendering, and creator-facing controls.",
    status: "active",
    priority: "critical",
    tags: ["lyrics", "video", "mcp", "music"],
    source: "GitHub",
    sourceUrl: "https://github.com/D0ubl3-A/illco-command/tree/main/app/tools/lyric-video-forge",
  },
  {
    id: "project-viral-stitch",
    kind: "project",
    area: "Creative Systems",
    title: "Viral Stitch AI",
    summary: "Music-aware and context-aware video editing system with clip matching, speed edits, lip-sync, character consistency, and generative frame editing.",
    status: "next",
    priority: "high",
    tags: ["video-editing", "lipsync", "creator"],
    source: "GitHub",
    sourceUrl: "https://github.com/D0ubl3-A/viral-stitch-ai",
  },
  {
    id: "project-faceless-youtube",
    kind: "project",
    area: "Creative Systems",
    title: "Faceless YouTube Channel Machine",
    summary: "Multi-niche channel operating system that creates scripts, voice, visuals, edits, thumbnails, style profiles, and publishing packages.",
    status: "next",
    priority: "high",
    tags: ["youtube", "automation", "faceless"],
    source: "ChatGPT project history",
  },
  {
    id: "project-uap-lab",
    kind: "project",
    area: "Research Products",
    title: "UAP AI Lab",
    summary: "AI-assisted research interface for released UFO and UAP files, evidence organization, source comparison, and public-facing exploration.",
    status: "active",
    priority: "medium",
    tags: ["uap", "research", "documents"],
    source: "GitHub",
    sourceUrl: "https://github.com/D0ubl3-A/UFO-USA",
  },
  {
    id: "project-safe-mlo",
    kind: "project",
    area: "Learning",
    title: "SAFE MLO Study Deck",
    summary: "Study application and collaborative two-player learning concept for mortgage-loan-originator exam preparation.",
    status: "active",
    priority: "high",
    tags: ["study", "mlo", "education"],
    source: "GitHub",
    sourceUrl: "https://github.com/D0ubl3-A/safe-mlo-study-deck",
  },
  {
    id: "project-agent-course",
    kind: "project",
    area: "Learning",
    title: "AI Agents Course 2026",
    summary: "Structured learning and portfolio work around AI agents, agent architecture, reliability, evaluation, and production deployment.",
    status: "active",
    priority: "medium",
    tags: ["agents", "course", "career"],
    source: "GitHub",
    sourceUrl: "https://github.com/D0ubl3-A/ai-agents-course-2026",
  },
  {
    id: "project-real-estate-commercials",
    kind: "project",
    area: "Real Estate",
    title: "Real Estate Commercial Generator",
    summary: "Production system for short real-estate commercials, listing scenes, captions, thumbnails, and buyer-focused funnels.",
    status: "active",
    priority: "high",
    tags: ["real-estate", "video", "lead-generation"],
    source: "GitHub",
    sourceUrl: "https://github.com/D0ubl3-A/real-estate-commercials-vercel",
  },
  {
    id: "project-record-label-platform",
    kind: "project",
    area: "Music Business",
    title: "AI Record Label Operating Platform",
    summary: "Label and artist accounts, release planning, distribution preparation, writers workshop, merch, video, social media, analytics, and rights workflows.",
    status: "next",
    priority: "high",
    tags: ["record-label", "distribution", "artists"],
    source: "ChatGPT project history",
  },
  {
    id: "music-m3ntally-ill",
    kind: "music",
    area: "Music",
    title: "M3ntally-iLL",
    summary: "Primary solo artist identity. Dark, horrorcore, Eastside-influenced creative direction with Christian conflict, Vegas imagery, and cinematic visual storytelling.",
    status: "active",
    priority: "critical",
    tags: ["artist", "horrorcore", "las-vegas"],
    source: "ChatGPT memory",
  },
  {
    id: "music-gods-hitman",
    kind: "music",
    area: "Music",
    title: "God's Hitman",
    summary: "Active M3ntally-iLL cover-art and release concept. Maintain face consistency with the approved artist reference image.",
    status: "next",
    priority: "high",
    tags: ["cover-art", "release", "m3ntally-ill"],
    source: "ChatGPT project history",
  },
  {
    id: "music-dying-soul",
    kind: "music",
    area: "Music",
    title: "Dying Soul animated video",
    summary: "24-fps full-motion animation project using consistent character assets, phonetic lip-sync, beat-aware motion, and internal-conflict imagery.",
    status: "active",
    priority: "high",
    tags: ["animation", "music-video", "lipsync"],
    source: "ChatGPT project history",
  },
  {
    id: "routine-friday-music",
    kind: "task",
    area: "Music",
    title: "Friday morning music push",
    summary: "Move M3ntally-iLL projects forward every Friday morning through cover art, lyric videos, release preparation, song sequencing, and lyrics.",
    status: "active",
    priority: "high",
    tags: ["weekly", "release-prep", "routine"],
    source: "Recurring plan",
  },
  {
    id: "product-lead-intake",
    kind: "product",
    area: "Products",
    title: "AI Lead Intake System",
    summary: "Store product priced at $499. Captures, qualifies, routes, and follows up with leads for service businesses.",
    status: "active",
    priority: "high",
    tags: ["leads", "automation", "$499"],
    source: "Product catalog",
  },
  {
    id: "product-missed-call",
    kind: "product",
    area: "Products",
    title: "AI Missed Call Text-Back",
    summary: "Store product priced at $399. Converts missed calls into immediate text conversations and lead-recovery workflows.",
    status: "active",
    priority: "high",
    tags: ["missed-call", "sms", "$399"],
    source: "Product catalog",
  },
  {
    id: "product-booking",
    kind: "product",
    area: "Products",
    title: "AI Appointment Booking + Confirm",
    summary: "Store product priced at $549. Books appointments and automates confirmations and follow-up.",
    status: "active",
    priority: "high",
    tags: ["booking", "appointments", "$549"],
    source: "Product catalog",
  },
  {
    id: "product-mastering",
    kind: "product",
    area: "Products",
    title: "Professional AI Music Mastering",
    summary: "AI-assisted mastering optimized for streaming platforms with 24-bit WAV and MP3 delivery, feedback cycles, and conversion-focused positioning.",
    status: "active",
    priority: "medium",
    tags: ["mastering", "music", "service"],
    source: "Product catalog",
  },
  {
    id: "system-agent-swarms",
    kind: "system",
    area: "Operations",
    title: "Agent swarm delivery model",
    summary: "Use coordinated research, architecture, implementation, QA, and publishing agents to compress large projects while preserving review gates and evidence.",
    status: "active",
    priority: "critical",
    tags: ["agents", "operations", "qa"],
    source: "Operating decision",
  },
  {
    id: "decision-orchestration",
    kind: "decision",
    area: "Creative Systems",
    title: "Orchestration beats one long generation",
    summary: "Build media systems as short controlled scenes with timing, continuity, QA gates, versioned artifacts, and final assembly rather than relying on one uncontrolled generation.",
    status: "active",
    priority: "high",
    tags: ["video", "architecture", "qa"],
    source: "Architecture decision",
  },
  {
    id: "decision-project-id",
    kind: "decision",
    area: "Operations",
    title: "Every production starts with one project ID",
    summary: "Track channel, series, status, owner, title, audience, promise, runtime, risk, deadline, budget, artifact versions, and approvals under one immutable project ID.",
    status: "active",
    priority: "high",
    tags: ["project-management", "provenance", "versioning"],
    source: "Faceless Channel OS",
  },
  {
    id: "content-unhinged-podcast",
    kind: "content",
    area: "Media",
    title: "The Unhinged Podcast",
    summary: "Political podcast currently focused on YouTube. Keep branding provocative without describing it as right-wing unless explicitly requested.",
    status: "active",
    priority: "medium",
    tags: ["podcast", "youtube", "politics"],
    source: "ChatGPT memory",
  },
  {
    id: "content-linkedin",
    kind: "content",
    area: "Marketing",
    title: "LinkedIn authority engine",
    summary: "Publish strong AI implementation, custom ChatGPT app, agent swarm, creator-tool, and small-business automation content that points to illcoai.tech.",
    status: "next",
    priority: "high",
    tags: ["linkedin", "seo", "thought-leadership"],
    source: "Content strategy",
    sourceUrl: "https://illcoai.tech",
  },
  {
    id: "task-seo-cleanup",
    kind: "task",
    area: "Marketing",
    title: "Clean duplicate blog URLs",
    summary: "Use the Drive cleanup workbook to noindex, delete, or merge duplicate programmatic posts and protect the strongest canonical pages.",
    status: "next",
    priority: "high",
    tags: ["seo", "duplicates", "canonical"],
    source: "Google Drive",
  },
  {
    id: "system-repository-inventory",
    kind: "system",
    area: "Engineering",
    title: "GitHub repository inventory",
    summary: "Initial connected scan found 51 repositories under D0ubl3-A, spanning production apps, experiments, music systems, research tools, study apps, and infrastructure.",
    status: "active",
    priority: "high",
    tags: ["github", "inventory", "repositories"],
    source: "GitHub",
    sourceUrl: "https://github.com/D0ubl3-A",
    metadata: { repositoryCount: 51, snapshotDate: "2026-07-12" },
  },
  {
    id: "system-drive-inventory",
    kind: "system",
    area: "Knowledge",
    title: "Google Drive knowledge inventory",
    summary: "Initial scan located the iLLCo business plan, product-listing assets, SEO cleanup workbooks, project folders, generation records, and current build notes.",
    status: "active",
    priority: "medium",
    tags: ["drive", "documents", "knowledge-base"],
    source: "Google Drive",
    metadata: { sampledResults: 25, snapshotDate: "2026-07-12" },
  },
  {
    id: "task-private-import",
    kind: "task",
    area: "Second Brain",
    title: "Import private memory pack",
    summary: "Load the private JSON export into Brain OS after signing in. Private Gmail, calendar, health, personal, and infrastructure details are deliberately not hardcoded into the public repository.",
    status: "next",
    priority: "critical",
    tags: ["privacy", "import", "memory"],
    source: "Brain OS bootstrap",
  },
];

export function createFallbackBrainSnapshot(ownerEmail: string): BrainSnapshot {
  const now = new Date().toISOString();
  const items: BrainItem[] = publicBrainSeed.map((item, index) => ({
    id: item.id || `fallback-${index + 1}`,
    ownerEmail,
    kind: item.kind || "memory",
    area: item.area || "General",
    title: item.title || "Untitled",
    summary: item.summary || "",
    status: item.status || "active",
    priority: item.priority || "medium",
    tags: item.tags || [],
    source: item.source || "Bootstrap",
    sourceUrl: item.sourceUrl || null,
    dueAt: item.dueAt || null,
    metadata: item.metadata || {},
    createdAt: now,
    updatedAt: now,
  }));

  return {
    items,
    total: items.length,
    active: items.filter((item) => item.status === "active").length,
    next: items.filter((item) => item.status === "next").length,
    blocked: items.filter((item) => item.status === "blocked").length,
    done: items.filter((item) => item.status === "done").length,
    areas: new Set(items.map((item) => item.area)).size,
    sources: [
      { name: "GitHub", state: "connected", detail: "51 repositories inventoried", itemCount: 51 },
      { name: "Google Drive", state: "connected", detail: "Business, product, SEO, and project files sampled", itemCount: 25 },
      { name: "ChatGPT memory", state: "seeded", detail: "Projects, brands, routines, and decisions loaded", itemCount: items.filter((item) => item.source.includes("ChatGPT")).length },
      { name: "Private import", state: "ready", detail: "JSON importer is ready for sensitive data", itemCount: 0 },
    ],
  };
}
