import { createServer } from "node:http";
import { readFileSync } from "node:fs";
import { promises as fs } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { registerAppResource, registerAppTool, RESOURCE_MIME_TYPE } from "@modelcontextprotocol/ext-apps/server";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { z } from "zod";

const ROOT=dirname(fileURLToPath(import.meta.url));
const PORT=Number(process.env.PORT??8787), MCP_PATH=process.env.MCP_PATH??"/mcp";
const DATA=resolve(process.env.PROJECT_G_DATA_FILE??resolve(ROOT,"data/project-g.json"));
const UI=resolve(ROOT,"public/project-g-command-center.html"), UI_URI="ui://ai-project-kickoff-builder/command-center-v1.html";
const html=readFileSync(UI,"utf8"); let writes=Promise.resolve();
const TOOLS=[
["get_project_g_tool_catalog","Tool catalog","read"],["list_project_g_projects","List projects","read"],["get_project_g_project","Open project","read"],
["update_project_g_progress","Update progress","write"],["update_project_g_contributors","Update contributors","write"],["validate_project_g_project","Validate project","read"],
["add_project_g_section_update","Add section update","write"],["add_project_g_note","Leave note","write"],["set_project_g_note_status","Resolve note","write"],
["run_project_g_assistant_action","Run with ChatGPT","write"],["export_project_g_markdown","Export status","read"],["render_project_g_dashboard","Render dashboard","read"]
].map(([name,title,mode])=>({name,title,mode,purpose:title,directUiAction:title}));
const clone=x=>JSON.parse(JSON.stringify(x));
function expand(x){if(!Array.isArray(x))return x;const[id,name,pct,ready,aaron,cody,goal]=x;return{projectId:id,name,businessGoal:goal,completionPercentage:pct,completionConfidence:ready>=55?"high":"medium",completionBasis:"Evidence-based estimate from visible planning, implementation, validation, deployment/operation, and governance evidence.",readinessScore:ready,readinessStatus:"needs_review",contributors:{"Aaron Allton":{visibleShare:aaron,work:[aaron?"Visible Project G evidence attributed to Aaron Allton, including the iLL Agency account.":"No contribution visible in the supplied Project G evidence."],aliases:["iLL Agency"]},"Cody Rose":{visibleShare:cody,work:[cody?"Visible Project G evidence attributed to Cody Rose.":"No contribution visible in the supplied Project G evidence."],aliases:[]}},criticalBlockers:["Confirmed owners, approvers, committed dates, communication cadence, and high-risk mitigation ownership require review."],sectionUpdates:[],notes:[],assistantRuns:[],history:[]}}
async function load(){const s=JSON.parse(await fs.readFile(DATA,"utf8"));s.projects=s.projects.map(expand);return s;}
async function save(s){const t=`${DATA}.${process.pid}.tmp`;s.revision=(s.revision??0)+1;s.updatedAt=new Date().toISOString();await fs.writeFile(t,JSON.stringify(s,null,2)+"\n");await fs.rename(t,DATA);}
async function mutate(fn){const job=writes.then(async()=>{const s=await load(), out=await fn(s);await save(s);return {s,out};});writes=job.catch(()=>{});return job;}
function project(s,id){const p=s.projects.find(x=>x.projectId===id||x.name===id);if(!p)throw new Error("Project not found");return p;}
function summary(s,filters={}){let ps=s.projects;const q=(filters.search??"").toLowerCase();if(q)ps=ps.filter(p=>(p.name+p.businessGoal).toLowerCase().includes(q));if(filters.status&&filters.status!=="all")ps=ps.filter(p=>p.readinessStatus===filters.status);if(filters.contributor&&filters.contributor!=="all")ps=ps.filter(p=>p.contributors[filters.contributor].visibleShare>0);return {revision:s.revision,updatedAt:s.updatedAt,summary:{projectCount:s.projects.length,portfolioCompletionPercentage:Math.round(s.projects.reduce((a,p)=>a+p.completionPercentage,0)/s.projects.length*10)/10,averageReadinessScore:Math.round(s.projects.reduce((a,p)=>a+p.readinessScore,0)/s.projects.length*10)/10,kickoffReady:s.projects.filter(p=>p.readinessStatus==="kickoff_ready").length,needsReview:s.projects.filter(p=>p.readinessStatus==="needs_review").length},filters:{search:filters.search??"",status:filters.status??"all",contributor:filters.contributor??"all"},selectedProjectId:filters.selectedProjectId??null,projects:clone(ps)};}
function validate(p){const blockers=[...(p.criticalBlockers??[])];return {projectId:p.projectId,projectName:p.name,kickoffReady:blockers.length===0,validationScore:blockers.length?50:100,blockers};}
const reply=(structuredContent,text)=>({structuredContent,content:[{type:"text",text}]});
const meta=(render=false)=>({securitySchemes:[{type:"noauth"}],...(render?{ui:{resourceUri:UI_URI,visibility:["model"]},"openai/outputTemplate":UI_URI}:{}),"openai/widgetAccessible":false});
function app(){const s=new McpServer({name:"ai-project-kickoff-builder",version:"1.0.0"},{instructions:"The widget emits PROJECT_G_PLUGIN_ACTION through ui/message. Parse it, call the relevant Project G tool, complete the work now, then call render_project_g_dashboard."});
registerAppResource(s,"ai-project-kickoff-builder-ui",UI_URI,{},async()=>({contents:[{uri:UI_URI,mimeType:RESOURCE_MIME_TYPE,text:html,_meta:{ui:{prefersBorder:true,csp:{connectDomains:[],resourceDomains:[]}},"openai/widgetDescription":"AI Project Kickoff Builder portfolio controller."}}]}));
registerAppTool(s,"get_project_g_tool_catalog",{title:"Project G tools",description:"List all Project G capabilities.",inputSchema:{},annotations:{readOnlyHint:true},securitySchemes:[{type:"noauth"}],_meta:meta()},async()=>reply({tools:TOOLS},`${TOOLS.length} tools available.`));
registerAppTool(s,"list_project_g_projects",{title:"List projects",description:"Search and filter Project G.",inputSchema:{search:z.string().optional(),status:z.enum(["all","kickoff_ready","needs_review"]).optional(),contributor:z.enum(["all","Aaron Allton","Cody Rose"]).optional()},annotations:{readOnlyHint:true},securitySchemes:[{type:"noauth"}],_meta:meta()},async input=>{const st=await load();return reply({dashboard:summary(st,input)},`Loaded ${st.projects.length} projects.`)});
registerAppTool(s,"get_project_g_project",{title:"Open project",description:"Load one authoritative project record.",inputSchema:{projectId:z.string()},annotations:{readOnlyHint:true},securitySchemes:[{type:"noauth"}],_meta:meta()},async({projectId})=>{const st=await load(),p=project(st,projectId);return reply({project:clone(p)},`${p.name} is ${p.completionPercentage}% complete.`)});
registerAppTool(s,"update_project_g_progress",{title:"Update progress",description:"Save evidence-based completion.",inputSchema:{projectId:z.string(),completionPercentage:z.number().int().min(0).max(100),completionConfidence:z.enum(["low","medium","high"]),basisNote:z.string().min(10)},annotations:{readOnlyHint:false,idempotentHint:true},securitySchemes:[{type:"noauth"}],_meta:meta()},async x=>{const r=await mutate(st=>{const p=project(st,x.projectId);Object.assign(p,{completionPercentage:x.completionPercentage,completionConfidence:x.completionConfidence,completionBasis:x.basisNote});return clone(p)});return reply({project:r.out,dashboard:summary(r.s,{selectedProjectId:x.projectId})},"Progress saved.")});
registerAppTool(s,"update_project_g_contributors",{title:"Update contributors",description:"Save Aaron/Cody evidence shares.",inputSchema:{projectId:z.string(),aaronVisibleShare:z.number().int().min(0).max(100),codyVisibleShare:z.number().int().min(0).max(100),aaronWorkNote:z.string(),codyWorkNote:z.string()},annotations:{readOnlyHint:false,idempotentHint:true},securitySchemes:[{type:"noauth"}],_meta:meta()},async x=>{if(x.aaronVisibleShare+x.codyVisibleShare!==100)throw new Error("Shares must total 100");const r=await mutate(st=>{const p=project(st,x.projectId);p.contributors["Aaron Allton"].visibleShare=x.aaronVisibleShare;p.contributors["Cody Rose"].visibleShare=x.codyVisibleShare;p.contributors["Aaron Allton"].work=[x.aaronWorkNote];p.contributors["Cody Rose"].work=[x.codyWorkNote];return clone(p)});return reply({project:r.out,dashboard:summary(r.s,{selectedProjectId:x.projectId})},"Contributors saved.")});
registerAppTool(s,"validate_project_g_project",{title:"Validate project",description:"Run kickoff readiness checks.",inputSchema:{projectId:z.string()},annotations:{readOnlyHint:true},securitySchemes:[{type:"noauth"}],_meta:meta()},async({projectId})=>{const st=await load(),v=validate(project(st,projectId));return reply({validation:v},v.kickoffReady?"Ready.":"Needs review.")});
registerAppTool(s,"add_project_g_section_update",{title:"Add update",description:"Save a section-specific update.",inputSchema:{projectId:z.string(),section:z.enum(["overview","actions","deliverables","risks","communications"]),author:z.enum(["Aaron Allton","Cody Rose","Team"]),updateText:z.string().min(1)},annotations:{readOnlyHint:false},securitySchemes:[{type:"noauth"}],_meta:meta()},async x=>{const r=await mutate(st=>{const p=project(st,x.projectId),u={id:`update_${Date.now()}`,section:x.section,author:x.author,text:x.updateText,createdAt:new Date().toISOString()};p.sectionUpdates.unshift(u);return clone(p)});return reply({project:r.out,dashboard:summary(r.s,{selectedProjectId:x.projectId})},"Update saved.")});
registerAppTool(s,"add_project_g_note",{title:"Leave note",description:"Leave Aaron/Cody/team note.",inputSchema:{projectId:z.string(),author:z.enum(["Aaron Allton","Cody Rose"]),recipient:z.enum(["Aaron Allton","Cody Rose","Team"]),section:z.string(),noteText:z.string().min(1)},annotations:{readOnlyHint:false},securitySchemes:[{type:"noauth"}],_meta:meta()},async x=>{const r=await mutate(st=>{const p=project(st,x.projectId),n={id:`note_${Date.now()}`,author:x.author,recipient:x.recipient,section:x.section,text:x.noteText,status:"open",createdAt:new Date().toISOString(),resolvedAt:null};p.notes.unshift(n);return clone(p)});return reply({project:r.out,dashboard:summary(r.s,{selectedProjectId:x.projectId})},"Note saved.")});
registerAppTool(s,"set_project_g_note_status",{title:"Resolve note",description:"Resolve or reopen a note.",inputSchema:{projectId:z.string(),noteId:z.string(),status:z.enum(["open","resolved"])},annotations:{readOnlyHint:false,idempotentHint:true},securitySchemes:[{type:"noauth"}],_meta:meta()},async x=>{const r=await mutate(st=>{const p=project(st,x.projectId),n=p.notes.find(n=>n.id===x.noteId);if(!n)throw new Error("Note not found");n.status=x.status;n.resolvedAt=x.status==="resolved"?new Date().toISOString():null;return clone(p)});return reply({project:r.out,dashboard:summary(r.s,{selectedProjectId:x.projectId})},"Note updated.")});
registerAppTool(s,"run_project_g_assistant_action",{title:"Run with ChatGPT",description:"Record and prepare a direct assistant action.",inputSchema:{projectId:z.string(),author:z.enum(["Aaron Allton","Cody Rose","Team"]),section:z.string(),action:z.string(),instruction:z.string().optional()},annotations:{readOnlyHint:false},securitySchemes:[{type:"noauth"}],_meta:meta()},async x=>{const r=await mutate(st=>{const p=project(st,x.projectId),run={id:`run_${Date.now()}`,author:x.author,section:x.section,action:x.action,instruction:x.instruction??"",createdAt:new Date().toISOString()};p.assistantRuns.unshift(run);return clone(p)});const prompt=`Execute ${x.action} now for ${r.out.name}, section ${x.section}. ${x.instruction??""} Use Project G tools, save verified changes, do not invent missing facts, and refresh the dashboard.`;return reply({project:r.out,assistantPrompt:prompt,requiredTools:TOOLS.map(t=>t.name)},prompt)});
registerAppTool(s,"export_project_g_markdown",{title:"Export status",description:"Create a Markdown report.",inputSchema:{projectId:z.string()},annotations:{readOnlyHint:true},securitySchemes:[{type:"noauth"}],_meta:meta()},async({projectId})=>{const st=await load(),p=project(st,projectId),md=`# ${p.name}\n\n- Completion: **${p.completionPercentage}%**\n- Readiness: **${p.readinessScore}/100**\n- Aaron: **${p.contributors["Aaron Allton"].visibleShare}%**\n- Cody: **${p.contributors["Cody Rose"].visibleShare}%**\n\n## Blockers\n${p.criticalBlockers.map(x=>`- ${x}`).join("\n")}`;return reply({fileName:`${p.projectId}.md`,markdown:md},"Report ready.")});
registerAppTool(s,"render_project_g_dashboard",{title:"Open command center",description:"Render or refresh the in-chat UI.",inputSchema:{selectedProjectId:z.string().optional(),search:z.string().optional(),status:z.enum(["all","kickoff_ready","needs_review"]).optional(),contributor:z.enum(["all","Aaron Allton","Cody Rose"]).optional()},annotations:{readOnlyHint:true},securitySchemes:[{type:"noauth"}],_meta:meta(true)},async input=>{const st=await load(),d=summary(st,input),p=input.selectedProjectId?project(st,input.selectedProjectId):st.projects[0];d.selectedProjectId=p?.projectId??null;return reply({dashboard:d,selectedProject:clone(p),toolCatalog:TOOLS},"Command center ready.")});return s;}
const http=createServer(async(req,res)=>{const url=new URL(req.url??"/",`http://${req.headers.host??"localhost"}`);if(url.pathname==="/healthz"){const s=await load();res.writeHead(200,{"content-type":"application/json"}).end(JSON.stringify({status:"ok",projects:s.projects.length,revision:s.revision}));return}if(url.pathname==="/preview"){const s=await load(),initial={dashboard:summary(s,{selectedProjectId:s.projects[0].projectId}),selectedProject:s.projects[0],toolCatalog:TOOLS};res.writeHead(200,{"content-type":"text/html"}).end(html.replace("<!--PREVIEW-->",`<script>window.__PREVIEW__=${JSON.stringify(initial).replaceAll("<","\\u003c")}</script>`));return}if(url.pathname===MCP_PATH&&req.method==="OPTIONS"){res.writeHead(204,{"access-control-allow-origin":"*","access-control-allow-methods":"POST,GET,DELETE,OPTIONS","access-control-allow-headers":"content-type,mcp-session-id,authorization"}).end();return}if(url.pathname===MCP_PATH){res.setHeader("access-control-allow-origin","*");const m=app(),t=new StreamableHTTPServerTransport({sessionIdGenerator:undefined,enableJsonResponse:true});res.on("close",()=>{t.close();m.close()});await m.connect(t);await t.handleRequest(req,res);return}res.writeHead(404).end("Not found")});
http.listen(PORT,()=>console.log(`AI Project Kickoff Builder: http://localhost:${PORT}${MCP_PATH}`));
