import type { AutoTubeStyleId } from "./types";

export type StyleDirective = {
  styleId: AutoTubeStyleId;
  audiencePromise: string;
  preproduction: string[];
  narrativeArchitecture: string[];
  assetStrategy: string[];
  animationDirection: string[];
  cameraAndComposition: string[];
  typographyDirection: string[];
  audioDirection: string[];
  editingDirection: string[];
  qualityGates: string[];
  requiredDeliverables: string[];
};

export const STYLE_DIRECTIVES: Record<AutoTubeStyleId, StyleDirective> = {
  "evidence-business-demo": {
    styleId: "evidence-business-demo",
    audiencePromise:
      "The prospect will see a credible, personalized future-state workflow that is clearly grounded in their real public business context.",
    preproduction: [
      "Capture the company name, website, location, services, audience, visible conversion path, contact channels, hours, and current calls to action.",
      "Create a dated evidence ledger. Separate observed facts from inferences, proposed workflows, and measured results.",
      "Map the current funnel from awareness through inquiry, qualification, conversion, delivery, retention, and referral.",
      "Select one high-value friction point that can be demonstrated visually in under ninety seconds.",
      "Define a narrowly scoped pilot with explicit inclusions, exclusions, dependencies, and owner approval points.",
    ],
    narrativeArchitecture: [
      "Open with the prospect identity and a specific observed friction within three seconds.",
      "Show the current-state moment where a lead, client, customer, or staff member encounters friction.",
      "Demonstrate the proposed workflow step by step using realistic interfaces and data states.",
      "Show the human handoff, controls, and exceptions before presenting outcomes.",
      "Close with a concrete pilot or walkthrough CTA, not a broad request to discuss AI.",
    ],
    assetStrategy: [
      "Use a real or faithfully recreated website view, clearly labeled as a concept when not live.",
      "Create distinct UI states for intake, qualification, scheduling, follow-up, handoff, and reporting as relevant.",
      "Use prospect branding only to demonstrate a private concept; never imply endorsement or deployment.",
      "Keep all example customer data fictional and non-sensitive.",
      "Provide source URLs for observed claims and archive screenshots when possible.",
    ],
    animationDirection: [
      "Animate cursor paths, taps, field completion, status changes, notifications, routing, and dashboard updates.",
      "Every interaction must cause a visible system state change.",
      "Use motion to show causality: input, decision, automation, human review, outcome.",
      "Change meaningful visual information every three to six seconds.",
      "Reserve decorative motion for transitions; workflow motion takes priority.",
    ],
    cameraAndComposition: [
      "Use controlled pushes and crops to direct attention to one interface action at a time.",
      "Keep interface text readable at mobile playback size.",
      "Use split-screen only when comparison or handoff genuinely benefits from simultaneous views.",
      "Maintain consistent browser, device, and dashboard framing.",
    ],
    typographyDirection: [
      "Use one concise claim or outcome per scene.",
      "Distinguish observed facts, proposed capabilities, and measured outcomes through labels or context.",
      "Use captions independent of interface labels.",
      "Avoid hype terms, guarantees, and unverified percentages.",
    ],
    audioDirection: [
      "Narration should sound consultative, specific, and restrained.",
      "Use subtle interface SFX for messages, confirmations, and status changes.",
      "Keep music supportive and low-complexity under narration.",
      "Pause narration briefly when a critical interface result needs visual attention.",
    ],
    editingDirection: [
      "Cut on completed actions and state changes rather than arbitrary timing.",
      "Do not hold any static interface frame longer than needed to understand it.",
      "Sequence the demo as a single believable job from entry through handoff.",
      "End on the exact deliverable or next step the prospect would receive.",
    ],
    qualityGates: [
      "Prospect identity is unmistakable in the first three seconds.",
      "All observed or measured claims have evidence IDs.",
      "At least sixty percent of scenes demonstrate actions instead of presenting slides.",
      "No scene implies that a concept mockup is already deployed.",
      "Regulated businesses preserve professional judgment and explicit human control.",
      "CTA names a concrete scope, time commitment, or pilot.",
    ],
    requiredDeliverables: [
      "evidence ledger",
      "current-state funnel map",
      "future-state workflow map",
      "scene manifest",
      "narration script",
      "caption file",
      "asset manifest",
      "quality report",
      "final render",
      "outreach message",
    ],
  },

  "product-ui-demo": {
    styleId: "product-ui-demo",
    audiencePromise:
      "The viewer will understand how the product works, what changes after each action, and what complete outcome the interface produces.",
    preproduction: [
      "Choose one primary user job and one measurable completion state.",
      "Map the exact click, type, selection, upload, processing, review, and export sequence.",
      "Identify states that must be real, simulated, mocked, or omitted.",
      "Prepare clean demo data and resettable product state.",
      "Define the minimum interface labels that must remain readable in the final aspect ratio.",
    ],
    narrativeArchitecture: [
      "Open on the completed result or the painful starting state.",
      "Return to the beginning and run one complete user journey.",
      "Reveal only the controls needed for the current step.",
      "Show the system processing, error handling, and final output where material.",
      "Close with the result, user value, and next action.",
    ],
    assetStrategy: [
      "Prefer real product capture or deterministic prototype states over generic UI mockups.",
      "Prepare high-resolution screens for every state transition.",
      "Use synthetic data that looks realistic but contains no personal or confidential information.",
      "Create fallback illustrations only for invisible backend operations.",
      "Maintain one device and browser visual system unless a cross-device flow is central.",
    ],
    animationDirection: [
      "Use cursor easing that feels intentional, not robotic or erratic.",
      "Show clicks, taps, keyboard entry, selection states, progress, success, and error recovery.",
      "Use callout motion only when the interface itself cannot communicate the change.",
      "Synchronize zooms and highlights to the exact interaction being narrated.",
      "Remove idle cursor movement and meaningless hover states.",
    ],
    cameraAndComposition: [
      "Keep a stable master frame and use nested crops for detail.",
      "Do not zoom so far that users lose interface context.",
      "Use match cuts between related product states.",
      "Return to the full product view at major milestones.",
    ],
    typographyDirection: [
      "Use annotations as short verbs or outcomes, not paragraphs.",
      "Avoid covering controls, data, or confirmation messages.",
      "Separate captions from UI text and keep both readable.",
      "Use consistent terminology matching the real product.",
    ],
    audioDirection: [
      "Narrate intent and consequence rather than reading labels aloud.",
      "Use restrained click, typing, upload, processing, and success sounds.",
      "Use music with a clear but unobtrusive pulse for pacing.",
      "Avoid SFX on every cursor movement.",
    ],
    editingDirection: [
      "Cut after state changes and before idle time.",
      "Speed-ramp repetitive typing while preserving key entered values.",
      "Use freeze moments only to explain critical decisions.",
      "Keep the complete workflow causally continuous.",
    ],
    qualityGates: [
      "Every interaction has a visible result.",
      "One complete user job reaches a final outcome.",
      "No unsupported product feature is simulated as functional.",
      "Interface and captions are readable at mobile size.",
      "The product remains identifiable throughout the sequence.",
    ],
    requiredDeliverables: [
      "user-job map",
      "interaction script",
      "state capture list",
      "scene manifest",
      "cursor and camera choreography",
      "caption file",
      "quality report",
      "final render",
    ],
  },

  "animated-explainer": {
    styleId: "animated-explainer",
    audiencePromise:
      "The viewer will grasp a complex idea through a coherent visual metaphor system that remains understandable even without audio.",
    preproduction: [
      "Reduce the topic to one central question and no more than five supporting concepts.",
      "Define a visual metaphor for each abstract concept.",
      "Create a design bible for shapes, icons, characters, line weight, perspective, palette, and texture.",
      "Map causal relationships and dependencies before storyboarding.",
      "Choose whether the explainer is character-led, diagram-led, object-led, or hybrid.",
    ],
    narrativeArchitecture: [
      "Hook with a visual paradox, relatable problem, or surprising transformation.",
      "Establish the mental model before introducing details.",
      "Build concepts incrementally and preserve prior visual context.",
      "Use a midpoint simplification or recap before the final implication.",
      "Resolve with a clear takeaway or action.",
    ],
    assetStrategy: [
      "Build reusable vector components and rigged character parts.",
      "Keep illustration perspective and lighting consistent.",
      "Design iconography for meaning rather than decoration.",
      "Create alternate expressions and poses for recurring characters.",
      "Prepare scene-safe backgrounds that do not compete with foreground motion.",
    ],
    animationDirection: [
      "Animate cause and effect through movement, transformation, connection, and separation.",
      "Use anticipation, follow-through, easing, and secondary motion deliberately.",
      "Vary motion language by semantic role: systems flow, characters act, ideas morph, data accumulates.",
      "Keep simultaneous focal animations limited to preserve comprehension.",
      "Use holds after complex transformations so the audience can process the result.",
    ],
    cameraAndComposition: [
      "Compose each scene around one dominant teaching objective.",
      "Use camera moves to reveal relationships, not merely add energy.",
      "Maintain spatial continuity across diagram expansions.",
      "Protect title-safe and caption-safe regions.",
    ],
    typographyDirection: [
      "Use text as labels, anchors, and memorable takeaways.",
      "Never duplicate the full narration on screen.",
      "Keep terminology stable across scenes.",
      "Animate key terms according to meaning rather than applying one preset universally.",
    ],
    audioDirection: [
      "Use narration with instructional warmth and precise pacing.",
      "Assign subtle sonic motifs to recurring concepts or characters.",
      "Use SFX to reinforce transformations and connections.",
      "Let music evolve with the conceptual arc.",
    ],
    editingDirection: [
      "Edit around comprehension beats, not only sentence boundaries.",
      "Allow visual setup before narration explains a new concept.",
      "Use match transformations to connect related ideas.",
      "Remove decorative shots that do not teach or advance the story.",
    ],
    qualityGates: [
      "Each abstract concept has a consistent visual representation.",
      "The story remains understandable with muted audio.",
      "Character and object identity stays consistent.",
      "No scene introduces more simultaneous concepts than the audience can track.",
      "The conclusion follows visibly from the demonstrated causal chain.",
    ],
    requiredDeliverables: [
      "concept hierarchy",
      "visual metaphor map",
      "style bible",
      "character sheets when used",
      "storyboard",
      "animation manifest",
      "narration and captions",
      "quality report",
      "final render",
    ],
  },

  "cinematic-brand-film": {
    styleId: "cinematic-brand-film",
    audiencePromise:
      "The viewer will feel the brand's values and desired future through a coherent cinematic world rather than a conventional sales presentation.",
    preproduction: [
      "Define the emotional promise, central human tension, and final feeling in one sentence each.",
      "Create a visual reference board for lensing, lighting, production design, palette, texture, and movement.",
      "Choose a protagonist, object, place, or ritual that carries the film.",
      "Design a shot progression with contrast in scale, energy, and intimacy.",
      "Plan continuity for wardrobe, environment, time of day, and screen direction.",
    ],
    narrativeArchitecture: [
      "Open with a compelling image or human moment before explaining the brand.",
      "Build tension through environment, action, and sensory detail.",
      "Reveal the brand or product as part of the resolution rather than an interruption.",
      "Use a visual motif that evolves across the film.",
      "End on an emotionally resolved image and minimal CTA.",
    ],
    assetStrategy: [
      "Create or source shots from one coherent visual world.",
      "Maintain character, wardrobe, prop, environment, and lighting continuity.",
      "Use inserts and macro shots to make texture and craft tangible.",
      "Prepare clean brand assets for restrained end-card use.",
      "Avoid mixed stock libraries with visibly different color science or camera quality.",
    ],
    animationDirection: [
      "Use naturalistic environmental motion and restrained graphic overlays.",
      "Apply parallax or camera motion only when it preserves photographic realism.",
      "Use slow reveals, rack-focus simulations, light movement, and texture motion where appropriate.",
      "Keep brand marks stable and confident rather than overanimated.",
    ],
    cameraAndComposition: [
      "Choose a consistent lens language and depth-of-field strategy.",
      "Use wide, medium, close, and macro shots with narrative purpose.",
      "Preserve screen direction and eyelines.",
      "Use camera movement to express pursuit, discovery, pressure, intimacy, or release.",
    ],
    typographyDirection: [
      "Keep copy minimal and editorial.",
      "Use typography as a cinematic object with measured entrances and exits.",
      "Avoid dense feature lists.",
      "Reserve the strongest type lockup for the final promise or brand reveal.",
    ],
    audioDirection: [
      "Build sound from atmosphere, tactile detail, music, and silence.",
      "Use music with a clear emotional arc and room for environmental sound.",
      "Design transitions sonically before relying on visual effects.",
      "Use narration only when it adds meaning unavailable through image and sound.",
    ],
    editingDirection: [
      "Cut for emotional progression, gaze, gesture, and sound bridges.",
      "Use visual and sonic motifs to create continuity.",
      "Vary shot duration intentionally; do not apply uniform pacing.",
      "Remove shots that are attractive but redundant.",
    ],
    qualityGates: [
      "The film has one coherent visual world.",
      "The emotional promise is legible without a feature list.",
      "Camera motion and transitions have narrative motivation.",
      "Audio and image work as one composition.",
      "The final frame resolves the opening tension.",
    ],
    requiredDeliverables: [
      "creative treatment",
      "reference board",
      "continuity bible",
      "shot list",
      "sound map",
      "edit map",
      "color treatment notes",
      "quality report",
      "final render",
    ],
  },

  "kinetic-typography": {
    styleId: "kinetic-typography",
    audiencePromise:
      "The words themselves will become an expressive visual performance with exceptional readability, rhythm, and rhetorical emphasis.",
    preproduction: [
      "Lock the final spoken or written text before animation.",
      "Mark emphasis, pause, contrast, repetition, escalation, and resolution.",
      "Choose no more than two primary type families and define a hierarchy system.",
      "Create a timing map at phrase, word, syllable, and beat levels as needed.",
      "Define when imagery supports type and when type must stand alone.",
    ],
    narrativeArchitecture: [
      "Open with the strongest phrase in the first visual beat.",
      "Build rhythm through contrast between dense and sparse moments.",
      "Use repetition with visual evolution.",
      "Create a midpoint pattern break.",
      "Resolve on one memorable phrase or action.",
    ],
    assetStrategy: [
      "Prepare font-safe text layouts for every aspect ratio.",
      "Use texture, shape, photography, or footage only when it strengthens the words.",
      "Create reusable emphasis treatments for numbers, contrasts, quotations, and CTAs.",
      "Keep backgrounds subordinate to text readability.",
    ],
    animationDirection: [
      "Animate phrase structure, not every character by default.",
      "Map motion to meaning: expansion, compression, interruption, echo, collision, disappearance, accumulation.",
      "Use velocity, scale, spacing, and direction as rhetorical tools.",
      "Protect reading time before transitioning away.",
      "Use beat sync selectively so semantic emphasis outranks mechanical rhythm.",
    ],
    cameraAndComposition: [
      "Treat the frame as a typographic stage with stable reading paths.",
      "Use camera movement only when moving through a designed type environment.",
      "Maintain safe margins and avoid edge collisions on mobile screens.",
      "Use negative space as an active pacing device.",
    ],
    typographyDirection: [
      "Establish explicit rules for case, weight, width, tracking, alignment, scale, and color.",
      "Limit simultaneous text to what can be read comfortably.",
      "Never distort type so far that letterforms become ambiguous.",
      "Use captions separately when the kinetic text is editorial rather than verbatim.",
    ],
    audioDirection: [
      "Lock animation to final voice or music timing.",
      "Use percussive and tonal SFX sparingly to reinforce major type actions.",
      "Allow silence to make visual emphasis stronger.",
      "Duck music under spoken lines without flattening rhythmic energy.",
    ],
    editingDirection: [
      "Edit at rhetorical beats and visual completion points.",
      "Create contrast between rapid sequences and deliberate holds.",
      "Use pattern breaks to reset attention.",
      "Avoid constant maximum motion.",
    ],
    qualityGates: [
      "Every phrase remains readable during and after motion.",
      "Motion reflects meaning or cadence.",
      "Hierarchy is clear in every paused frame.",
      "The final message is understandable without narration.",
      "No scene presents paragraph-length kinetic text.",
    ],
    requiredDeliverables: [
      "locked script",
      "rhetorical timing map",
      "type system",
      "frame layouts",
      "animation cue sheet",
      "audio sync map",
      "quality report",
      "final render",
    ],
  },

  "character-story": {
    styleId: "character-story",
    audiencePromise:
      "The audience will follow consistent characters through meaningful actions and emotional change rather than watching disconnected poses or generic narration.",
    preproduction: [
      "Define each main character's goal, obstacle, personality, visual identity, and end state.",
      "Create turnaround sheets, expression sheets, wardrobe rules, scale references, and prop assignments.",
      "Map locations and screen geography.",
      "Lock dialogue and narration before lip-sync planning.",
      "Write action beats that can be communicated visually.",
    ],
    narrativeArchitecture: [
      "Introduce the protagonist through action.",
      "Establish a clear want and obstacle.",
      "Escalate through choices and consequences.",
      "Use the product, idea, or intervention as part of the character's action rather than an external lecture.",
      "End with a visible change in situation, behavior, or emotion.",
    ],
    assetStrategy: [
      "Maintain stable character reference images or models across every scene.",
      "Prepare reusable poses, mouth shapes, hand shapes, and expressions.",
      "Create consistent environments with mapped entrances, exits, and landmarks.",
      "Assign props consistently and preserve scale.",
      "Use background characters only when they support the main action.",
    ],
    animationDirection: [
      "Prioritize pose-to-pose clarity, anticipation, action, reaction, and follow-through.",
      "Use facial expression and body language together.",
      "Animate hands and eyelines intentionally.",
      "Lock lip sync to final audio and preserve phoneme timing.",
      "Use secondary motion for clothing, hair, props, and environment without distracting from acting.",
    ],
    cameraAndComposition: [
      "Maintain screen direction and eyeline continuity.",
      "Choose shot size based on action and emotion.",
      "Avoid cutting during an unreadable action pose.",
      "Use establishing shots when geography changes.",
    ],
    typographyDirection: [
      "Keep text minimal unless the story explicitly uses messages, signs, or interfaces.",
      "Use captions that do not cover faces, hands, or important action.",
      "Maintain dialogue attribution when multiple characters speak.",
    ],
    audioDirection: [
      "Use final dialogue before lip-sync animation.",
      "Create distinct voice, movement, prop, and environment sound layers.",
      "Use room tone and ambience for continuity.",
      "Score emotional turns rather than every physical action.",
    ],
    editingDirection: [
      "Cut on action, reaction, eyeline, or emotional turn.",
      "Allow reaction shots enough time to register.",
      "Use continuity editing unless a deliberate stylistic break is defined.",
      "Remove dialogue that repeats what the acting already communicates.",
    ],
    qualityGates: [
      "Character identity, wardrobe, proportions, and voice remain consistent.",
      "Every scene contains meaningful action or reaction.",
      "Screen geography and eyelines remain coherent.",
      "Lip sync uses locked audio.",
      "The protagonist's ending state differs meaningfully from the opening.",
    ],
    requiredDeliverables: [
      "character bible",
      "expression and pose sheets",
      "environment map",
      "locked dialogue",
      "action storyboard",
      "animation and lip-sync manifest",
      "sound map",
      "quality report",
      "final render",
    ],
  },

  "social-performance-ad": {
    styleId: "social-performance-ad",
    audiencePromise:
      "The viewer will understand the problem, mechanism, proof, offer, and next action before attention drops.",
    preproduction: [
      "Define one audience, one painful or desired state, one mechanism, one proof type, one offer, and one CTA.",
      "Generate multiple hooks and score them for specificity, novelty, relevance, and visual potential.",
      "Choose the platform, placement, aspect ratio, sound-on and sound-off behavior, and duration limit.",
      "Identify truthful proof assets and disclose concept footage when necessary.",
      "Create a first-frame test that communicates value without playback.",
    ],
    narrativeArchitecture: [
      "Hook in the first one to two seconds.",
      "Name or show the problem immediately.",
      "Demonstrate the mechanism, not only the benefit.",
      "Present proof before the offer.",
      "Make the offer concrete and finish with one low-friction CTA.",
    ],
    assetStrategy: [
      "Prioritize vertical-safe closeups, product views, interface details, transformation proof, and concise type.",
      "Create alternate opening frames for hook testing.",
      "Prepare proof cards, testimonial clips, result screens, or demonstrations with source context.",
      "Avoid generic stock footage unrelated to the mechanism.",
    ],
    animationDirection: [
      "Front-load motion and visual contrast without overwhelming comprehension.",
      "Use kinetic type for the hook, mechanism, proof, and CTA.",
      "Animate counters and proof only when values are sourced.",
      "Change meaningful visual information every one to three seconds.",
      "Use pattern interrupts strategically, not continuously.",
    ],
    cameraAndComposition: [
      "Design mobile-first with center-safe focal points.",
      "Use close framing and rapid scale changes for attention resets.",
      "Keep brand recognition present without sacrificing the hook.",
      "Ensure CTA remains visible long enough to act.",
    ],
    typographyDirection: [
      "Use short, high-contrast phrases readable in under one second.",
      "Write for silent viewing.",
      "Avoid multiple simultaneous claims.",
      "Use legally and factually defensible urgency.",
    ],
    audioDirection: [
      "Use an immediate sonic hook or vocal opening.",
      "Sync major edits to rhythm while preserving spoken comprehension.",
      "Use impact sounds sparingly for proof and CTA moments.",
      "Ensure the ad still works fully muted.",
    ],
    editingDirection: [
      "Remove setup that does not increase curiosity or comprehension.",
      "Cut before energy decays.",
      "Use proof as a narrative beat, not an end-card footnote.",
      "Create multiple hook variants from one body edit.",
    ],
    qualityGates: [
      "The first frame communicates tension, benefit, or curiosity.",
      "The mechanism is visible.",
      "Proof appears before the CTA.",
      "The offer is specific and singular.",
      "The ad works with audio muted.",
      "No false scarcity, guarantees, or unsupported metrics appear.",
    ],
    requiredDeliverables: [
      "audience and offer brief",
      "hook matrix",
      "first-frame variants",
      "proof manifest",
      "scene and animation manifest",
      "caption file",
      "platform variants",
      "quality report",
      "final renders",
    ],
  },

  "documentary-case-study": {
    styleId: "documentary-case-study",
    audiencePromise:
      "The viewer will trust the transformation because the film shows real context, process, human testimony, evidence, and limitations.",
    preproduction: [
      "Verify participant consent, release status, claim sources, dates, baselines, and measurement methods.",
      "Create a chronology of the original state, intervention, implementation, obstacles, and results.",
      "Identify testimony that adds firsthand context rather than repeating marketing copy.",
      "Plan interviews, observational footage, documents, screenshots, and data visuals.",
      "Define what cannot be shown and how it will be disclosed.",
    ],
    narrativeArchitecture: [
      "Open on a human or operational consequence.",
      "Establish the original condition with evidence.",
      "Introduce the intervention and show implementation work.",
      "Include complications, learning, or limits to preserve credibility.",
      "Present measured outcomes with baseline and timeframe.",
      "Close with the participant's perspective and an appropriately scoped CTA.",
    ],
    assetStrategy: [
      "Use real interviews, work environments, process footage, documents, dashboards, and dated records.",
      "Label reenactments, simulations, and concept visuals.",
      "Maintain source metadata for every chart, quote, and result.",
      "Capture room tone, cutaways, hands, tools, and environmental detail.",
    ],
    animationDirection: [
      "Use restrained lower thirds, timelines, document highlights, maps, and chart reveals.",
      "Animate data progressively to show reasoning.",
      "Avoid dramatic effects that undermine documentary trust.",
      "Use subtle parallax only on archival stills when appropriate.",
    ],
    cameraAndComposition: [
      "Use interview framing consistent with participant role and tone.",
      "Capture observational sequences with clear beginning, middle, and end.",
      "Maintain visual distinction between present-day footage and archival material.",
      "Use cutaways to support claims and edit naturally.",
    ],
    typographyDirection: [
      "Identify speakers and sources clearly.",
      "Display metric units, dates, baselines, and timeframes.",
      "Keep disclosure text readable.",
      "Avoid promotional superlatives unsupported by participants or data.",
    ],
    audioDirection: [
      "Prioritize clean dialogue and natural environment sound.",
      "Use music to support structure without manipulating testimony.",
      "Preserve authentic pauses and emotional texture.",
      "Use sound bridges to connect process stages.",
    ],
    editingDirection: [
      "Edit quotes without changing meaning.",
      "Intercut claims with supporting process or evidence.",
      "Preserve chronological and causal clarity.",
      "Include meaningful limitations where they affect interpretation.",
    ],
    qualityGates: [
      "All participants and assets have appropriate permission.",
      "Quotes retain original meaning and context.",
      "Metrics include baseline, timeframe, unit, and source.",
      "Reenactments and simulations are disclosed.",
      "The process between problem and outcome is visible.",
    ],
    requiredDeliverables: [
      "consent and release ledger",
      "evidence ledger",
      "interview guide",
      "chronology",
      "shot list",
      "transcript and selects",
      "data visualization plan",
      "quality report",
      "final render",
    ],
  },

  "before-after-transformation": {
    styleId: "before-after-transformation",
    audiencePromise:
      "The viewer will see a fair, controlled, and visually undeniable comparison between original and improved states.",
    preproduction: [
      "Define the before state, intervention, after state, measurement conditions, and elapsed time.",
      "Lock matched camera, crop, scale, lighting, device state, or data axes.",
      "Identify variables that cannot be controlled and disclose them.",
      "Capture intermediate process evidence.",
      "Decide whether the comparison is visual, operational, financial, behavioral, or mixed.",
    ],
    narrativeArchitecture: [
      "Open with a direct matched comparison or unresolved original state.",
      "Explain the intervention briefly.",
      "Show the process or mechanism responsible for change.",
      "Reveal the after state using matched framing.",
      "Quantify only what is measured fairly.",
      "Close with the scope and next action.",
    ],
    assetStrategy: [
      "Capture before and after assets under matched conditions.",
      "Maintain original files and metadata.",
      "Create split views, wipes, overlays, difference maps, or synchronized playback as appropriate.",
      "Include process assets so the transformation does not appear magical.",
    ],
    animationDirection: [
      "Use mask wipes, match cuts, overlays, and synchronized transitions.",
      "Animate measured differences with clearly labeled units.",
      "Do not morph reality when intermediate frames could mislead.",
      "Allow viewers to pause on the comparison.",
    ],
    cameraAndComposition: [
      "Match framing, perspective, scale, and focal point.",
      "Use stable reference markers when useful.",
      "Avoid camera motion during the core comparison unless both states share it exactly.",
    ],
    typographyDirection: [
      "Label before, intervention, after, timeframe, and conditions.",
      "Keep comparison text symmetrical.",
      "Avoid exaggerated adjectives when the visual evidence is sufficient.",
    ],
    audioDirection: [
      "Use sound to mark reveal and transition without overstating the result.",
      "Narrate conditions and mechanism concisely.",
      "Keep music secondary to visual comparison.",
    ],
    editingDirection: [
      "Preserve enough hold time for direct comparison.",
      "Show process before the final reveal when causality matters.",
      "Use repeated matched comparisons for different dimensions only when each adds new information.",
    ],
    qualityGates: [
      "Comparison conditions are matched or disclosed.",
      "The intervention is visible.",
      "No deceptive morphing or axis manipulation is used.",
      "Measured claims include timeframe and method.",
      "The transformation remains clear in a paused frame.",
    ],
    requiredDeliverables: [
      "comparison protocol",
      "before asset set",
      "process asset set",
      "after asset set",
      "measurement notes",
      "comparison storyboard",
      "quality report",
      "final render",
    ],
  },

  "data-story": {
    styleId: "data-story",
    audiencePromise:
      "The viewer will follow a rigorous chain from question to evidence to pattern to implication without being overwhelmed or misled.",
    preproduction: [
      "Define one decision question and the audience action the data should inform.",
      "Audit sources, dates, units, denominators, missing data, uncertainty, and comparability.",
      "Select the simplest chart form for each question.",
      "Write the insight before designing the chart.",
      "Create a source ledger and transformation log.",
    ],
    narrativeArchitecture: [
      "Open with the question, contradiction, or surprising signal.",
      "Establish baseline and context.",
      "Reveal one dimension at a time.",
      "Compare only after units and scales are understood.",
      "Explain uncertainty or limitations before the final implication.",
      "End with the decision or next investigation.",
    ],
    assetStrategy: [
      "Use clean charts, maps, timelines, tables, counters, and annotated source documents.",
      "Keep raw and transformed data separate.",
      "Prepare accessible labels and alternative text summaries.",
      "Avoid unnecessary decorative graphics.",
    ],
    animationDirection: [
      "Reveal axes, baseline, series, comparison, and annotation in logical order.",
      "Use motion to preserve object constancy between chart states.",
      "Animate counters only when the number itself is central.",
      "Highlight one takeaway at a time.",
    ],
    cameraAndComposition: [
      "Keep charts large enough to read without aggressive zooming.",
      "Use camera pushes to isolate a point, then return to context.",
      "Maintain consistent scale and chart placement across comparisons.",
    ],
    typographyDirection: [
      "Show units, timeframe, source, denominator, and uncertainty where relevant.",
      "Write annotations as insights, not labels alone.",
      "Avoid excessive decimal precision.",
      "Use consistent number formatting.",
    ],
    audioDirection: [
      "Narrate interpretation rather than reading every value.",
      "Use subtle tones for reveal, threshold, and comparison moments.",
      "Keep music minimal enough that dense reasoning remains clear.",
    ],
    editingDirection: [
      "Allow reading time proportional to chart complexity.",
      "Do not cut before the audience can compare values.",
      "Use progressive disclosure instead of presenting complete dashboards instantly.",
      "Return to the original question before the conclusion.",
    ],
    qualityGates: [
      "Every chart answers one explicit question.",
      "Units, sources, dates, and denominators are available.",
      "Axes and scales remain honest and comparable.",
      "Uncertainty and limitations are represented where material.",
      "The conclusion is supported by the displayed evidence.",
    ],
    requiredDeliverables: [
      "decision question",
      "source ledger",
      "data transformation log",
      "chart specification",
      "storyboard",
      "animation cue sheet",
      "accessibility summary",
      "quality report",
      "final render",
    ],
  },

  "mixed-media-collage": {
    styleId: "mixed-media-collage",
    audiencePromise:
      "The viewer will experience a rich editorial world where diverse media feel intentionally art-directed rather than randomly layered.",
    preproduction: [
      "Define one unifying palette, texture family, edge treatment, shadow logic, and compositional grid.",
      "Collect photography, screenshots, illustrations, paper textures, marks, and type with clear rights or provenance.",
      "Assign each media type a narrative role.",
      "Create a density map showing where visual complexity rises and falls.",
      "Choose a recurring motif that connects scenes.",
    ],
    narrativeArchitecture: [
      "Open with a visually surprising composite that still has one focal point.",
      "Build meaning through juxtaposition and transformation.",
      "Use recurring motifs with variation.",
      "Create a deliberate visual reset before the final statement.",
      "Resolve with a cleaner, more stable final frame.",
    ],
    assetStrategy: [
      "Normalize resolution, color treatment, grain, edge softness, and lighting across source assets.",
      "Create separated layers for foreground, middle ground, background, texture, and type.",
      "Prepare cutout masks and alternate crops.",
      "Avoid low-resolution assets that break under camera movement.",
    ],
    animationDirection: [
      "Use depth through parallax, stagger, scale, rotation, mask reveals, and paper-like motion.",
      "Give layers distinct mass and inertia.",
      "Animate collage assembly and disassembly with clear hierarchy.",
      "Limit simultaneous movements so the focal point remains stable.",
    ],
    cameraAndComposition: [
      "Use a consistent editorial grid beneath apparent chaos.",
      "Keep one dominant focal element per frame.",
      "Use camera travel through layers to create depth.",
      "Protect text contrast from texture and overlapping assets.",
    ],
    typographyDirection: [
      "Integrate type as a physical collage layer while preserving readability.",
      "Use controlled variety within one hierarchy system.",
      "Avoid more than two primary type families.",
      "Use labels, stamps, handwriting, or annotations only when they fit the art direction.",
    ],
    audioDirection: [
      "Use tactile paper, tape, camera, marker, impact, and texture sounds selectively.",
      "Sync major assembly moments to music structure.",
      "Avoid stacking SFX as densely as visual layers.",
      "Use sound to differentiate material types.",
    ],
    editingDirection: [
      "Alternate dense sequences with visual breathing room.",
      "Use match shapes, textures, and colors across cuts.",
      "Build escalation through increasing layer complexity, then simplify for resolution.",
      "Remove assets that do not add meaning, rhythm, or depth.",
    ],
    qualityGates: [
      "Every frame has one clear focal point.",
      "Media sources share a coherent treatment.",
      "Layer motion creates depth rather than noise.",
      "Text remains readable against texture.",
      "Asset rights or provenance are documented.",
    ],
    requiredDeliverables: [
      "art direction board",
      "asset rights ledger",
      "layer manifest",
      "density map",
      "storyboard",
      "animation cue sheet",
      "sound palette",
      "quality report",
      "final render",
    ],
  },

  "music-driven-visualizer": {
    styleId: "music-driven-visualizer",
    audiencePromise:
      "The visuals will behave like a true interpretation of the track's rhythm, structure, lyrics, and emotion rather than a generic looping equalizer.",
    preproduction: [
      "Analyze tempo, meter, beat grid, sections, transitions, drops, breaks, instrumentation, energy, lyrics, metaphors, nouns, verbs, and emotional arc.",
      "Create a time-coded music map from beginning to end.",
      "Define a visual motif and energy range for each song section.",
      "Choose whether the piece is lyric-led, character-led, abstract, performance-led, or hybrid.",
      "Verify lyric and music rights for the intended use.",
    ],
    narrativeArchitecture: [
      "Use the intro to establish the visual world and motif.",
      "Let verses develop story, detail, or environment.",
      "Use choruses for visual expansion and recognizable recurring language.",
      "Use bridges, breaks, and drops for pattern change.",
      "Evolve repeated sections rather than replaying identical visuals.",
      "Resolve in alignment with the track's final musical and lyrical state.",
    ],
    assetStrategy: [
      "Create section-specific environments, palettes, typography, characters, particles, or symbols.",
      "Prepare lyric timing and safe text layouts when lyrics are displayed.",
      "Build reusable reactive layers with controlled parameter ranges.",
      "Create unique hero visuals for major musical peaks.",
    ],
    animationDirection: [
      "Map low-frequency energy, percussion, melody, vocals, and section changes to different visual parameters.",
      "Use beat sync at meaningful accents rather than every beat.",
      "Vary motion intensity, camera energy, particle density, color, and cut frequency by section.",
      "Interpret lyric meaning through imagery, action, metaphor, or typography.",
      "Use repetition with evolution.",
    ],
    cameraAndComposition: [
      "Design camera behavior per section: stable verse, expanding chorus, disrupted bridge, resolved outro as appropriate.",
      "Maintain focal clarity during high-energy moments.",
      "Use spatial movement to mirror musical build and release.",
    ],
    typographyDirection: [
      "Display only licensed or user-supplied lyrics.",
      "Time lyrics at phrase or word level according to vocal delivery.",
      "Use typographic motion that reflects pronunciation, rhythm, and meaning.",
      "Keep lyric text readable despite reactive backgrounds.",
    ],
    audioDirection: [
      "Use the source track as the timing authority.",
      "Do not add SFX that conflict with the mix unless intentionally designed.",
      "Preserve audio quality and avoid unnecessary re-encoding.",
      "Use stems when legally available for more precise reactivity.",
    ],
    editingDirection: [
      "Edit against the full song structure, not a uniform beat grid.",
      "Create contrast between sections.",
      "Land major cuts and transformations on musically meaningful events.",
      "Avoid exhausting the strongest visual effects before the musical peak.",
    ],
    qualityGates: [
      "The complete track has a time-coded structural map.",
      "Visual changes correspond to musical or lyrical reasons.",
      "Repeated sections evolve.",
      "Lyrics remain accurate, timed, readable, and rights-compliant.",
      "The visual peak aligns with the musical peak.",
    ],
    requiredDeliverables: [
      "music analysis map",
      "lyric and rights record",
      "section treatment map",
      "beat and event markers",
      "asset manifest",
      "animation parameter map",
      "quality report",
      "final render",
    ],
  },

  custom: {
    styleId: "custom",
    audiencePromise:
      "The final video will follow an explicit custom creative system instead of using custom as permission for generic or inconsistent output.",
    preproduction: [
      "Define the purpose, audience, intent, duration, aspect ratio, platform, constraints, references, and success criteria.",
      "Write a custom style constitution covering composition, motion, camera, typography, color, sound, pacing, transitions, and prohibited patterns.",
      "Choose which standard AutoTube disciplines are inherited and which are overridden.",
      "Define objective quality gates before asset generation.",
    ],
    narrativeArchitecture: [
      "Specify the exact narrative or experiential arc.",
      "Define required opening, midpoint, and ending states.",
      "State how each scene advances the viewer's understanding, emotion, or action.",
    ],
    assetStrategy: [
      "Specify asset types, sources, continuity rules, rights, and fallback behavior.",
      "Define which assets must be unique and which may repeat.",
      "Create an explicit layer and resolution contract.",
    ],
    animationDirection: [
      "Define motion vocabulary, density, timing, easing, hierarchy, and semantic purpose.",
      "Specify prohibited animation shortcuts.",
      "Require keyframes or procedural parameters for nonstandard motion.",
    ],
    cameraAndComposition: [
      "Define framing, lens or projection language, spatial continuity, and focal hierarchy.",
      "Specify safe areas and platform adaptations.",
    ],
    typographyDirection: [
      "Define type families, hierarchy, case, weight, scale, tracking, animation, captions, and accessibility.",
    ],
    audioDirection: [
      "Define narration, dialogue, music, SFX, ambience, silence, sync, loudness, and rights requirements.",
    ],
    editingDirection: [
      "Define pacing, cut logic, transition logic, pattern changes, and end-state behavior.",
    ],
    qualityGates: [
      "The custom style constitution is complete before generation.",
      "The output can be scored objectively against stated rules.",
      "Custom choices remain consistent across the complete video.",
      "No missing rule silently falls back to a generic slideshow.",
    ],
    requiredDeliverables: [
      "custom style constitution",
      "creative treatment",
      "scene manifest",
      "asset manifest",
      "animation manifest",
      "audio map",
      "quality rubric",
      "quality report",
      "final render",
    ],
  },
};

export function getStyleDirective(styleId: AutoTubeStyleId) {
  return STYLE_DIRECTIVES[styleId];
}
